---
- name: Install V2Ray
  pacman:
    name: v2ray
    state: "{{ 'latest' if v2ray_latest else 'present' }}"
    update_cache: yes
  notify: restart v2ray

- name: Copy V2Ray config
  copy:
    src: "{{ v2ray_config }}"
    dest: "{{ v2ray_config_target | default(_v2ray_config_target, true) }}"
    mode: "0644"
    backup: yes
  notify: restart v2ray
  when: v2ray_config is defined

- name: Enable V2Ray service
  service:
    name: v2ray
    enabled: yes
