---
- name: Include OpenWrt variables
  include_vars: OpenWRT.yml

- name: opkg add kuoruan-public.key
  shell: wget -O kuoruan-public.key http://openwrt.kuoruan.net/packages/public.key && opkg-key add kuoruan-public.key && rm kuoruan-public.key
  args:
    chdir: /tmp
    creates: /etc/opkg/keys/628987e0831fe551

- name: Get architecture
  shell: . /etc/openwrt_release; echo $DISTRIB_ARCH
  register: architecture
  changed_when: no
  check_mode: no

- name: Add opkg feeds
  lineinfile:
    path: /etc/opkg/customfeeds.conf
    regex: '^src/gz {{ item.name }} '
    line: src/gz {{ item.name }} {{ item.url }}
  when: item.enabled|default(True)
  with_items:
  - name: kuoruan_packages
    url: http://openwrt.kuoruan.net/packages/releases/{{ architecture.stdout }}
  - name: kuoruan_universal
    url: http://openwrt.kuoruan.net/packages/releases/all
    enabled: '{{ luci }}'
  register: opkg_feeds

- name: opkg update
  command: opkg update
  when: opkg_update or opkg_feeds.changed

- name: Install dnsmasq-full
  opkg:
    name: dnsmasq-full
    force: overwrite

- name: Install V2Ray
  opkg:
    name: '{{ item.name }}'
    state: '{{ item.state | default("present") }}'
  when: item.enabled|default(True)
  with_items:
  - name: 'v2ray-core{{ "-mini" if minimal else "" }}'
  - name: dnsmasq
    state: absent
    enabled: '{{ luci }}'
  - name: luci-compat
    enabled: '{{ luci }}'
  - name: luci-app-v2ray
    enabled: '{{ luci }}'

- name: Ensure V2Ray is latest
  command: opkg upgrade v2ray-core{{ "-mini" if minimal else "" }} luci-app-v2ray
  register: _opkg_upgrade
  changed_when: _opkg_upgrade.stdout != ""
  when: v2ray_latest

- name: Copy V2Ray config
  copy:
    src: "{{ v2ray_config }}"
    dest: "{{ v2ray_config_target | default(_v2ray_config_target, true) }}"
    mode: "0600"
    backup: yes
  when: v2ray_config is defined
  notify: restart v2ray

- name: Install libustream for CHNRoute and GFWList update
  block:
  - name: Install libustream-openssl for CHNRoute and GFWList update
    opkg:
      name: "{{ _libustream_openssl }}"
  rescue:
  - name: Install libustream-mbedtls for CHNRoute and GFWList update
    opkg:
      name: "{{ _libustream_mbedtls }}"
  when: not minimal
